# Blog info
blog_name: Forsigner
slogan: Find the bug of the world

# For seo
keywords: forsigner,前端,设计,Hexo主题,前端开发,用户体验,设计,frontend,design,nodejs,JavaScript

# Stats
google_analytics:
baidu_analytics: 57e94d016e201fba3603a8a2b0263af0

favicon:

# social
disqus_shortname: forsigner
# duoshuo_shortname: forsigner

show_count: true

home_nav:
  - Blog: /archives
  - Github: https://github.com/forsigner
  - Douban: http://www.douban.com/people/forsigner/
  - Twitter: https://twitter.com/forsigner

# config page nav (盒子)
page_nav:
  - 首页: /
  - 博客: /archives/
  - 分类: /category/
  - 标签: /tags/
  - 关于: /about/
  - RSS: /atom.xml
